# Generated by Django 5.1.6 on 2025-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_view', '0002_alter_pessoafisica_cpf_alter_pessoafisica_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('distancia', models.DecimalField(decimal_places=2, help_text='Distância em quilômetros', max_digits=5)),
                ('duracao', models.DurationField(help_text='Duração estimada (formato: HH:MM:SS)')),
                ('nivel_dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito Difícil')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('guias', models.ManyToManyField(related_name='trilhas_guiadas', to='home_view.pessoafisica')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['nome'],
            },
        ),
    ]
