# Generated by Django 5.1.7 on 2025-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('phone', models.CharField(max_length=16, verbose_name='Celular')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('phone', models.CharField(max_length=16, verbose_name='Celular')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nome do Empreendimento')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('region', models.CharField(max_length=255, verbose_name='Região')),
                ('business_phone', models.CharField(max_length=16, verbose_name='Telefone do Empreendimento')),
                ('business_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail do Empreendimento')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
